### PR TITLE
Change Mac-line endings to Unix style

### PR DESCRIPTION
**Pull request by tibbon**
The Mac-style line endings were making browsing the files on modern systems difficult. Using `mac2unix` I fixed up the line endings for all non-binary files when possible. 

I didn't touch any of the .u files

### CODE REVIEW

**Comment by blanham** [comment]
This /might/ break compiling with CodeWarrior?

**Comment by ernestask** [comment]
~`core.autocrlf` is your friend if you really need CRLF endings.~

Edit: nevermind, I forgot that old Macs used only CR.

Edit 2: mentioning the line endings in the README might be good to communicate the fact that this is intentional to keep compatibility, otherwise avid readers will keep proposing this change.

**Comment by akien-mga** [comment]
> This /might/ break compiling with CodeWarrior?

It would be good to get it tested to confirm. If CodeWarrior can handle LF, converting everything to LF (apart from proprietary files parsed by the engine that might expect CR for now) would really help with potential porting efforts.

**Comment by winterheart** [comment]
Hello.

There also *.ASM files, make sure that lines fixed for them too.

**Pull request closed without merging**
